ALTER TABLE public.logistica_bodegas 
ADD COLUMN IF NOT EXISTS tipo VARCHAR(100),
ADD COLUMN IF NOT EXISTS identificador INTEGER,
ADD COLUMN IF NOT EXISTS proveedor VARCHAR(255),
ADD COLUMN IF NOT EXISTS responsable VARCHAR(255),
ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(255),
ADD COLUMN IF NOT EXISTS estado VARCHAR(100);
