-- Create Empresa Cliente table
CREATE TABLE IF NOT EXISTS public.empresa_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Tipo Cliente table
CREATE TABLE IF NOT EXISTS public.tipo_cliente_empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Rutas / Origenes table
CREATE TABLE IF NOT EXISTS public.rutas_origen_destino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruta TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.empresa_cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipo_cliente_empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas_origen_destino ENABLE ROW LEVEL SECURITY;

-- Setup access to authenticated users
CREATE POLICY "Allow all actions for authenticated users on empresa_cliente" ON public.empresa_cliente FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for authenticated users on tipo_cliente_empresa" ON public.tipo_cliente_empresa FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all actions for authenticated users on rutas_origen_destino" ON public.rutas_origen_destino FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert dummy data if empty
INSERT INTO public.empresa_cliente (nombre) 
SELECT 'TransCompany S.A.' 
WHERE NOT EXISTS (SELECT 1 FROM public.empresa_cliente);

INSERT INTO public.tipo_cliente_empresa (nombre) 
SELECT 'Particular' 
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_cliente_empresa);

INSERT INTO public.tipo_cliente_empresa (nombre) 
SELECT 'Corporativo' 
WHERE NOT EXISTS (SELECT 1 FROM public.tipo_cliente_empresa);

INSERT INTO public.rutas_origen_destino (ruta) 
SELECT 'Aeropuerto - Centro' 
WHERE NOT EXISTS (SELECT 1 FROM public.rutas_origen_destino);
