import {
  BarChart3,
  Settings,
  Truck,
  Wrench,
  Package,
  ShoppingCart,
  Users,
  MapPin,
  ClipboardList,
  Activity,
  FileText,
  DollarSign,
  TrendingUp,
  Cpu,
  Boxes,
  Briefcase,
  AlertCircle,
  Menu,
  Bell,
  Search,
  UserCircle,
  CircleDashed,
  Droplet,
  Archive,
  CalendarClock,
  FileSpreadsheet,
  ScanBarcode,
  CheckSquare,
  Zap,
  Clock
} from 'lucide-react';

export const navigation = [
  {
    title: 'Super Administrador',
    icon: Settings,
    href: '/super-admin',
    submodules: [
      { title: 'Gestión de Empresas', icon: Briefcase, href: '/super-admin/empresas' },
      { title: 'Gestión de Perfiles y Permisos', icon: Users, href: '/super-admin/perfiles' },
      { title: 'Visión de Evolución', icon: TrendingUp, href: '/super-admin/vision-evolucion' },
    ],
  },
  {
    title: 'Dashboard & Estrategia',
    icon: BarChart3,
    href: '/dashboard',
    submodules: [
      { title: 'KPI Flota', icon: Activity, href: '/dashboard/kpi-flota' },
      { title: 'KPI RR.HH.', icon: Users, href: '/dashboard/kpi-rrhh' },
      { title: 'Análisis de Fallas', icon: AlertCircle, href: '/dashboard/fallas' },
      { title: 'Panel TCO', icon: DollarSign, href: '/dashboard/tco' },
      { title: 'Reporte Maestro', icon: FileSpreadsheet, href: '/dashboard/reporte-maestro' },
    ],
  },
  {
    title: 'Operaciones y Servicios',
    icon: MapPin,
    href: '/operaciones',
    submodules: [
      { title: 'Gestión de Servicios', icon: ClipboardList, href: '/operaciones/servicios' },
      { title: 'Programación', icon: CalendarClock, href: '/operaciones/programacion' },
      { title: 'GPS FleetSat', icon: MapPin, href: '/operaciones/gps' },
      { title: 'CHECK-IN', icon: CheckSquare, href: '/operaciones/checkin' },
      { title: 'Salida de Insumos', icon: Package, href: '/operaciones/insumos' },
      { title: 'Alertas', icon: AlertCircle, href: '/operaciones/alertas' },
    ],
  },
  {
    title: 'Gestión de Flota',
    icon: Truck,
    href: '/flota',
    submodules: [
      { title: 'Pizarra de Mantenimiento', icon: Wrench, href: '/flota/mantenimiento' },
      { title: 'Órdenes de Trabajo (OT)', icon: FileText, href: '/flota/ot' },
      { title: 'Gestión de Neumáticos', icon: CircleDashed, href: '/flota/neumaticos' },
      { title: 'Control de Combustible', icon: Droplet, href: '/flota/combustible' },
      { title: 'Vehículos Archivados', icon: Archive, href: '/flota/archivo' },
    ],
  },
  {
    title: 'Logística y Suministros',
    icon: Boxes,
    href: '/logistica',
    submodules: [
      { title: 'Gestión de Suministros', icon: Package, href: '/logistica/suministros' },
      { title: 'Gestión de Bodegas', icon: Boxes, href: '/logistica/bodegas' },
      { title: 'Terminal de Escaneo', icon: ScanBarcode, href: '/logistica/escaneo' },
      { title: 'Validaciones', icon: CheckSquare, href: '/logistica/validaciones' },
      { title: 'Auditorías', icon: ClipboardList, href: '/logistica/auditorias' },
    ],
  },
  {
    title: 'Compras y Proveedores',
    icon: ShoppingCart,
    href: '/compras',
    submodules: [
      { title: 'Órdenes de Compra', icon: ShoppingCart, href: '/compras/ordenes' },
      { title: 'Ingreso de Facturas', icon: FileText, href: '/compras/facturas' },
      { title: 'Proveedores', icon: Users, href: '/compras/proveedores' },
      { title: 'Contratos', icon: Briefcase, href: '/compras/contratos' },
      { title: 'Precio de Combustible', icon: DollarSign, href: '/compras/precio-combustible' },
    ],
  },
  {
    title: 'Configuración y Herramientas',
    icon: Settings,
    href: '/configuracion',
    submodules: [
      { title: 'Configuración Empresa', icon: Settings, href: '/configuracion/empresa' },
      { title: 'Usuarios y Cargos', icon: Users, href: '/configuracion/usuarios' },
      { title: 'Tareas y Pautas', icon: ClipboardList, href: '/configuracion/tareas' },
      { title: 'Tipos de Pausa', icon: Clock, href: '/configuracion/pausas' },
      { title: 'Pulser AI', icon: Cpu, href: '/configuracion/ai' },
      { title: 'Carga Masiva', icon: Zap, href: '/configuracion/carga-masiva' },
    ],
  },
];
