import {
  BarChart3,
  Settings,
  Truck,
  Wrench,
  Package,
  ShoppingCart,
  Users,
  MapPin,
  ClipboardList,
  Activity,
  FileText,
  FileCheck,
  DollarSign,
  TrendingUp,
  Cpu,
  Boxes,
  Briefcase,
  AlertCircle,
  Menu,
  Bell,
  Search,
  UserCircle,
  CircleDashed,
  Droplet,
  Archive,
  CalendarClock,
  FileSpreadsheet,
  ScanBarcode,
  CheckSquare,
  Calendar,
  Zap,
  Clock,
  HelpCircle,
  MessageSquare,
  Link,
  BookOpen,
  Map as MapIcon
} from 'lucide-react';

export const navigation = [
  {
    title: 'Super Administrador',
    icon: Settings,
    href: '/super-admin',
    submodules: [
      { title: 'Gestión de Empresas', icon: Briefcase, href: '/super-admin/empresas' },
      { title: 'Gestión de Perfiles y Permisos', icon: Users, href: '/super-admin/perfiles' },
      { title: 'Visión de Evolución', icon: TrendingUp, href: '/super-admin/vision-evolucion' },
    ],
  },
  {
    title: 'Dashboard & Estrategia',
    icon: BarChart3,
    href: '/dashboard',
    submodules: [
      { title: 'Dashboard', icon: BarChart3, href: '/dashboard' },
      { title: 'KPI Flota', icon: Activity, href: '/dashboard/kpi-flota' },
      { title: 'KPI RR.HH.', icon: Users, href: '/dashboard/kpi-rrhh' },
      { title: 'Análisis de Fallas', icon: AlertCircle, href: '/dashboard/fallas' },
      { title: 'Panel TCO', icon: DollarSign, href: '/dashboard/tco' },
      { title: 'Reporte Maestro', icon: FileSpreadsheet, href: '/dashboard/reporte-maestro' },
    ],
  },
  {
    title: 'Operaciones y Servicios',
    icon: MapPin,
    href: '/operaciones',
    submodules: [
      { title: 'Contratos Clientes', icon: Briefcase, href: '/operaciones/contratos' },
      { title: 'Crear Servicio', icon: ClipboardList, href: '/operaciones/servicios' },
      { title: 'Reservas', icon: Calendar, href: '/operaciones/reservas' },
      { title: 'Programación', icon: CalendarClock, href: '/operaciones/programacion' },
      { title: 'Control Documental', icon: FileCheck, href: '/operaciones/control-documental' },
      { title: 'Historial', icon: Activity, href: '/operaciones/historial' },
      { title: 'GPS FleetSat', icon: MapPin, href: '/operaciones/gps' },
      { title: 'Portal Conductor', icon: UserCircle, href: '/operaciones/portal-conductor' },
    ],
  },
  {
    title: 'Gestión de Flota',
    icon: Truck,
    href: '/flota',
    submodules: [
      { title: 'Alertas', icon: AlertCircle, href: '/flota/alertas' },
      { title: 'Pizarra de Mantenimiento', icon: Wrench, href: '/flota/mantenimiento' },
      { title: 'Pizarra de Programación', icon: Calendar, href: '/flota/programacion' },
      { title: 'Órdenes de Trabajo (OT)', icon: FileText, href: '/flota/ordenes-trabajo' },
      { title: 'Gestión de Neumáticos', icon: CircleDashed, href: '/flota/neumaticos' },
      { title: 'Control de Combustible', icon: Droplet, href: '/flota/combustible' },
    ],
  },
  {
    title: 'Logística y Suministros',
    icon: Boxes,
    href: '/logistica',
    submodules: [
      { title: 'Gestión de Suministros', icon: Package, href: '/logistica/suministros' },
      { title: 'Gestión de Bodegas', icon: Boxes, href: '/logistica/bodegas' },
      { title: 'Puerto de Escaneo', icon: ScanBarcode, href: '/logistica/escaneo' },
      { title: 'Aprobaciones', icon: CheckSquare, href: '/logistica/validaciones' },
      { title: 'Auditorías', icon: ClipboardList, href: '/logistica/auditorias' },
    ],
  },
  {
    title: 'Compras y Proveedores',
    icon: ShoppingCart,
    href: '/compras',
    submodules: [
      { title: 'Órdenes de Compra', icon: ShoppingCart, href: '/compras/ordenes' },
      { title: 'Ingreso de Facturas', icon: FileText, href: '/compras/facturas' },
      { title: 'Proveedores', icon: Users, href: '/compras/proveedores' },
      { title: 'Cotizaciones', icon: FileText, href: '/compras/cotizaciones' },
      { title: 'Contrato Proveedores', icon: Briefcase, href: '/compras/contratos' },
    ],
  },
  {
    title: 'Finanzas',
    icon: DollarSign,
    href: '/finanzas',
    submodules: [
      { title: 'Estado de Pago', icon: ClipboardList, href: '/finanzas/estado-pago' },
      { title: 'Registros Financieros', icon: FileText, href: '/finanzas/registros-financieros' },
      { title: 'Gestión Operativa', icon: Activity, href: '/finanzas/gestion-operativa' },
      { title: 'Historial Facturación', icon: FileText, href: '/finanzas/historial-facturacion' },
      { title: 'Costos Operacionales', icon: DollarSign, href: '/finanzas/costos' },
      { title: 'Presupuestos', icon: Activity, href: '/finanzas/presupuestos' },
      { title: 'Trazabilidad', icon: Activity, href: '/finanzas/trazabilidad' },
      { title: 'Evaluación Empresa', icon: Briefcase, href: '/finanzas/evaluacion-empresa' },
    ],
  },
  {
    title: 'Configuración y Herramientas',
    icon: Settings,
    href: '/configuracion',
    submodules: [
      { title: 'Gestión de Empresa', icon: Settings, href: '/configuracion/empresa' },
      { title: 'Personal', icon: Users, href: '/configuracion/personal' },
      { title: 'Asignación de Cargos', icon: UserCircle, href: '/configuracion/permisos' },
      { title: 'Integración GPS', icon: MapPin, href: '/configuracion/gps' },
      { title: 'Precio de Combustible', icon: DollarSign, href: '/configuracion/precio-combustible' },
      { title: 'Gestión de Pautas', icon: FileText, href: '/configuracion/pautas' },
      { title: 'Gestión de Tareas', icon: ClipboardList, href: '/configuracion/tareas' },
      { title: 'Gestión de Fallas', icon: AlertCircle, href: '/configuracion/fallas' },
      { title: 'Gestión de Vehículos', icon: Archive, href: '/configuracion/vehiculos' },
      { title: 'Kit de Repuestos', icon: Package, href: '/herramientas/kits' },
      { title: 'Gestión de Pausas', icon: Clock, href: '/configuracion/pausas' },
      { title: 'Gestión de Rutas', icon: MapIcon, href: '/configuracion/rutas' },
      { title: 'Carga Masiva', icon: Zap, href: '/configuracion/carga-masiva' },
    ],
  },
  {
    title: 'Soporte y Ayuda',
    icon: HelpCircle,
    href: '/soporte',
    submodules: [
      { title: 'Integraciones', icon: Link, href: '/soporte/integraciones' },
      { title: 'Centro de Ayuda', icon: MessageSquare, href: '/soporte/tickets' },
      { title: 'Manual de Uso', icon: BookOpen, href: '/soporte/manual' },
    ],
  },
];
