import {
  BarChart3,
  Settings,
  Truck,
  Wrench,
  Package,
  ShoppingCart,
  Users,
  MapPin,
  ClipboardList,
  Activity,
  FileText,
  FileCheck,
  DollarSign,
  TrendingUp,
  Cpu,
  Boxes,
  Briefcase,
  AlertCircle,
  Menu,
  Bell,
  Search,
  UserCircle,
  CircleDashed,
  Droplet,
  Archive,
  CalendarClock,
  FileSpreadsheet,
  ScanBarcode,
  CheckSquare,
  Calendar,
  Zap,
  Clock,
  HelpCircle,
  MessageSquare,
  Link,
  BookOpen,
  Map as MapIcon,
  Factory,
  PenTool,
  History,
  Shield,
  ShieldCheck,
  Eye
} from 'lucide-react';

export const navigation = [
  {
    title: 'Super Administrador',
    icon: Settings,
    href: '/super-admin',
    submodules: [
      { title: 'GestiÃ³n de Empresas', icon: Briefcase, href: '/super-admin/empresas' },
      { title: 'GestiÃ³n de Perfiles y Permisos', icon: Users, href: '/super-admin/perfiles' },
      { title: 'VisiÃ³n de EvoluciÃ³n', icon: TrendingUp, href: '/super-admin/vision-evolucion' },
      { title: 'Log de Actividad', icon: Activity, href: '/super-admin/actividad' },
    ],
  },
  {
    title: 'Dashboard & Estrategia',
    icon: BarChart3,
    href: '/dashboard',
    submodules: [
      { title: 'Dashboard', icon: BarChart3, href: '/dashboard' },
      { title: 'KPI Flota', icon: Activity, href: '/dashboard/kpi-flota' },
      { title: 'KPI RR.HH.', icon: Users, href: '/dashboard/kpi-rrhh' },
      { title: 'AnÃ¡lisis de Fallas', icon: AlertCircle, href: '/dashboard/fallas' },
      { title: 'Panel TCO', icon: DollarSign, href: '/dashboard/tco' },
      { title: 'Reporte Maestro', icon: FileSpreadsheet, href: '/dashboard/reporte-maestro' },
    ],
  },
  {
    title: 'Operaciones y Servicios',
    icon: MapPin,
    href: '/operaciones',
    submodules: [
      { title: 'Contratos Clientes', icon: Briefcase, href: '/operaciones/contratos' },
      { title: 'Crear Servicio', icon: ClipboardList, href: '/operaciones/servicios' },
      { title: 'Reservas', icon: Calendar, href: '/operaciones/reservas' },
      { title: 'Mantenedores', icon: ClipboardList, href: '/operaciones/mantenedores' },
      { title: 'ProgramaciÃ³n', icon: CalendarClock, href: '/operaciones/programacion' },
      { title: 'Control Documental', icon: FileCheck, href: '/operaciones/control-documental' },
      { title: 'Historial', icon: Activity, href: '/operaciones/historial' },
      { title: 'GPS FleetSat', icon: MapPin, href: '/operaciones/gps' },
      { title: 'Portal Conductor', icon: UserCircle, href: '/operaciones/portal-conductor' },
      { title: 'GestiÃ³n de Rutas', icon: MapIcon, href: '/operaciones/rutas' },
    ],
  },
  {
    title: 'ProducciÃ³n',
    icon: Factory,
    href: '/produccion',
    submodules: [
      { title: 'Dashboard de ProducciÃ³n', icon: BarChart3, href: '/produccion/dashboard' },
      { title: 'Control Sanny', icon: FileSpreadsheet, href: '/produccion/control-sanny' },
      { title: 'Reportes Diarios Transporte', icon: Truck, href: '/produccion/reportes-transporte' },
      { title: 'Reportes Diarios Mina', icon: PenTool, href: '/produccion/reportes-mina' },
      { title: 'Resumen Mensual Mina', icon: FileSpreadsheet, href: '/produccion/resumen-mensual-mina' },
      { title: 'Horas MÃ¡quina y Disponibilidad', icon: Clock, href: '/produccion/horas-maquina' },
      { title: 'Planificador Transporte', icon: CalendarClock, href: '/produccion/planificador' },
      { title: 'Trazabilidad', icon: History, href: '/produccion/trazabilidad' },
    ],
  },
  {
    title: 'GestiÃ³n de Flota',
    icon: Truck,
    href: '/flota',
    submodules: [
      { title: 'Alertas', icon: AlertCircle, href: '/flota/alertas' },
      { title: 'Pizarra de Mantenimiento', icon: Wrench, href: '/flota/mantenimiento' },
      { title: 'Pizarra de ProgramaciÃ³n', icon: Calendar, href: '/flota/programacion' },
      { title: 'Ã“rdenes de Trabajo (OT)', icon: FileText, href: '/flota/ordenes-trabajo' },
      { title: 'GestiÃ³n de NeumÃ¡ticos', icon: CircleDashed, href: '/flota/neumaticos' },
      { title: 'Control de Combustible', icon: Droplet, href: '/flota/combustible' },
    ],
  },
  {
    title: 'LogÃ­stica y Suministros',
    icon: Boxes,
    href: '/logistica',
    submodules: [
      { title: 'GestiÃ³n de Suministros', icon: Package, href: '/logistica/suministros' },
      { title: 'GestiÃ³n de Bodegas', icon: Boxes, href: '/logistica/bodegas' },
      { title: 'Puerto de Escaneo', icon: ScanBarcode, href: '/logistica/escaneo' },
      { title: 'AuditorÃ­a de Salidas', icon: CheckSquare, href: '/logistica/auditoria-salidas' },
      { title: 'Aprobaciones', icon: CheckSquare, href: '/logistica/validaciones' },
      { title: 'AuditorÃ­as', icon: ClipboardList, href: '/logistica/auditorias' },
    ],
  },
  {
    title: 'Compras y Proveedores',
    icon: ShoppingCart,
    href: '/compras',
    submodules: [
      { title: 'Panel de Solicitudes', icon: FileText, href: '/compras/solicitudes' },
      { title: 'Ã“rdenes de Compra', icon: ShoppingCart, href: '/compras/ordenes' },
      { title: 'Ingreso de Facturas', icon: FileText, href: '/compras/facturas' },
      { title: 'Proveedores', icon: Users, href: '/compras/proveedores' },
      { title: 'Cotizaciones', icon: FileText, href: '/compras/cotizaciones' },
      { title: 'Contrato Proveedores', icon: Briefcase, href: '/compras/contratos' },
    ],
  },
/* {
    title: 'Finanzas',
    icon: DollarSign,
    href: '/finanzas',
    submodules: [
      { title: 'Estado de Pago', icon: ClipboardList, href: '/finanzas/estado-pago' },
      { title: 'Registros Financieros', icon: FileText, href: '/finanzas/registros-financieros' },
      { title: 'GestiÃ³n Operativa', icon: Activity, href: '/finanzas/gestion-operativa' },
      { title: 'Historial FacturaciÃ³n', icon: FileText, href: '/finanzas/historial-facturacion' },
      { title: 'Costos Operacionales', icon: DollarSign, href: '/finanzas/costos' },
      { title: 'Presupuestos', icon: Activity, href: '/finanzas/presupuestos' },
      { title: 'Trazabilidad', icon: Activity, href: '/finanzas/trazabilidad' },
      { title: 'EvaluaciÃ³n Empresa', icon: Briefcase, href: '/finanzas/evaluacion-empresa' },
    ],
  }, */
  {
    title: 'Recursos Humanos',
    icon: Users,
    href: '/recursos-humanos',
    submodules: [
      { title: 'Personal', icon: Users, href: '/recursos-humanos/personal' },
      { title: 'AsignaciÃ³n de Cargos', icon: UserCircle, href: '/recursos-humanos/permisos' },
      { title: 'Turnos', icon: CalendarClock, href: '/recursos-humanos/turnos' },
    ],
  },
/* {
    title: 'Biblioteca TÃ©cnica',
    icon: BookOpen,
    href: '/biblioteca',
    submodules: [
      { title: 'Explorar Documentos', icon: Search, href: '/biblioteca/explorador' },
      { title: 'Subir Documento', icon: FileCheck, href: '/biblioteca/subir' },
    ],
  }, */
  {
    title: 'SSO / PrevenciÃ³n',
    icon: ShieldCheck,
    href: '/seguridad',
    submodules: [
      { title: 'Dashboard', icon: BarChart3, href: '/seguridad/dashboard' },
      { title: 'Trabajadores', icon: Users, href: '/seguridad/trabajadores' },
      { title: 'Empresas Contratistas', icon: Briefcase, href: '/seguridad/contratistas' },
      { title: 'Control Documental', icon: FileCheck, href: '/seguridad/documental' },
      { title: 'EPP', icon: Shield, href: '/seguridad/epp' },
      { title: 'Control Extintores', icon: Activity, href: '/seguridad/extintores' },
      { title: 'Equipos de Emergencia', icon: AlertCircle, href: '/seguridad/equipos-emergencia' },
      { title: 'Charlas', icon: MessageSquare, href: '/seguridad/charlas' },
      { title: 'Capacitaciones', icon: BookOpen, href: '/seguridad/capacitaciones' },
      { title: 'GestiÃ³n de Riesgos', icon: AlertCircle, href: '/seguridad/riesgos' },
      { title: 'Inspecciones', icon: CheckSquare, href: '/seguridad/inspecciones' },
      { title: 'Reporte Flash', icon: Zap, href: '/seguridad/reporte-flash' },
      { title: 'Incidentes / Accidentes', icon: AlertCircle, href: '/seguridad/incidentes' },
      { title: 'Observaciones', icon: Eye, href: '/seguridad/observaciones' },
      { title: 'Hallazgos', icon: Search, href: '/seguridad/hallazgos' },
      { title: 'Acciones Correctivas', icon: Wrench, href: '/seguridad/acciones-correctivas' },
      { title: 'Emergencias', icon: AlertCircle, href: '/seguridad/emergencias' },
      { title: 'AuditorÃ­as', icon: ClipboardList, href: '/seguridad/auditorias' },
      { title: 'Cumplimiento Normativo', icon: FileText, href: '/seguridad/normativo' },
      { title: 'Indicadores SSO', icon: TrendingUp, href: '/seguridad/indicadores' },
      { title: 'Reportes', icon: FileSpreadsheet, href: '/seguridad/reportes' },
    ],
  },
  {
    title: 'ConfiguraciÃ³n y Herramientas',
    icon: Settings,
    href: '/configuracion',
    submodules: [
      { title: 'GestiÃ³n de Empresa', icon: Settings, href: '/configuracion/empresa' },
      { title: 'Configuracin de Alertas', icon: Bell, href: '/configuracion/alertas' },
      { title: 'IntegraciÃ³n GPS', icon: MapPin, href: '/configuracion/gps' },
      { title: 'Precio de Combustible', icon: DollarSign, href: '/configuracion/precio-combustible' },
      { title: 'GestiÃ³n de Pautas', icon: FileText, href: '/configuracion/pautas' },
      { title: 'GestiÃ³n de Tareas', icon: ClipboardList, href: '/configuracion/tareas' },
      { title: 'GestiÃ³n de Fallas', icon: AlertCircle, href: '/configuracion/fallas' },
      { title: 'GestiÃ³n de VehÃ­culos', icon: Archive, href: '/configuracion/vehiculos' },
      { title: 'Kit de Repuestos', icon: Package, href: '/herramientas/kits' },
      { title: 'GestiÃ³n de Pausas', icon: Clock, href: '/configuracion/pausas' },
      { title: 'Carga Masiva', icon: Zap, href: '/configuracion/carga-masiva' },
    ],
  },
  {
    title: 'Soporte y Ayuda',
    icon: HelpCircle,
    href: '/soporte',
    submodules: [
      { title: 'Integraciones', icon: Link, href: '/soporte/integraciones' },
      { title: 'Centro de Ayuda', icon: MessageSquare, href: '/soporte/tickets' },
      { title: 'Manual de Uso', icon: BookOpen, href: '/soporte/manual' },
    ],
  },
];
